// Copyright (C) 1999-2000 Id Software, Inc.
//


#define INVENTORY_NONE				0
//armor
#define INVENTORY_ARMOR				1
//weapons
#define INVENTORY_GAUNTLET			4
#define INVENTORY_SHOTGUN			5
#define INVENTORY_MACHINEGUN		6
#define INVENTORY_GRENADELAUNCHER	7
#define INVENTORY_ROCKETLAUNCHER	8
#define INVENTORY_LIGHTNING			9
#define INVENTORY_RAILGUN			10
#define INVENTORY_PLASMAGUN			11
#define INVENTORY_BFG10K			13
#define INVENTORY_GRAPPLINGHOOK		14
#define INVENTORY_NAILGUN			15
#define INVENTORY_PROXLAUNCHER		16
#define INVENTORY_CHAINGUN			17
//ammo
#define INVENTORY_SHELLS			18
#define INVENTORY_BULLETS			19
#define INVENTORY_GRENADES			20
#define INVENTORY_CELLS				21
#define INVENTORY_LIGHTNINGAMMO		22
#define INVENTORY_ROCKETS			23
#define INVENTORY_SLUGS				24
#define INVENTORY_BFGAMMO			25
#define INVENTORY_NAILS				26
#define INVENTORY_MINES				27
#define INVENTORY_BELT				28
//powerups
#define INVENTORY_HEALTH			29
#define INVENTORY_TELEPORTER		30
#define INVENTORY_MEDKIT			31
#define INVENTORY_KAMIKAZE			32
#define INVENTORY_PORTAL			33
#define INVENTORY_INVULNERABILITY	34
#define INVENTORY_QUAD				35
#define INVENTORY_ENVIRONMENTSUIT	36
#define INVENTORY_HASTE				37
#define INVENTORY_INVISIBILITY		38
#define INVENTORY_REGEN				39
#define INVENTORY_FLIGHT			40
#define INVENTORY_SCOUT				41
#define INVENTORY_GUARD				42
#define INVENTORY_DOUBLER			43
#define INVENTORY_AMMOREGEN			44

#define INVENTORY_REDFLAG			45
#define INVENTORY_BLUEFLAG			46
#define INVENTORY_NEUTRALFLAG		47
#define INVENTORY_REDCUBE			48
#define INVENTORY_BLUECUBE			49

//PKMOD -Add Weapons. 
//PKMOD - Ergodic - 09/06/00 added PKA weight definition
//PKMOD - Ergodic - 04/15/01 - move definitions to begin with 50
#define INVENTORY_BEANS					50
#define INVENTORY_GRAVITY				51
#define INVENTORY_SENTRY				52
#define INVENTORY_TRAP					53
#define INVENTORY_AIRFIST				54
#define INVENTORY_EXPLOSIVESHELLS		55
#define INVENTORY_EXPLOSIVESHOTGUN		56
//PKMOD - Ergodic - 12/17/00 rename NAILS to PKA_NAILS to resolve 1.27g conflict
#define INVENTORY_PKA_NAILS				57
//PKMOD - Ergodic - 12/17/00 rename NAILGUN to PKA_NAILGUN to resolve 1.27g conflict
#define INVENTORY_PKA_NAILGUN			58
//PKMOD - Ergodic 07/09/00 try to get bots to display the attached beartrap
#define INVENTORY_BEARTRAPS_ATTACHED	59

//PKMOD - Ergodic - 09/07/00 added PKA Ammo counts
#define INVENTORY_GRAVITY_AMMO			60
#define INVENTORY_SENTRY_AMMO			61
#define INVENTORY_TRAP_AMMO				62

//PKMOD - Ergodic - 10/31/01 - new PKA holdables
#define INVENTORY_RADIATE				63

//PKMOD - Ergodic - 11/23/01 - new PKA holdables
#define INVENTORY_PERSENTRY				64

//PKMOD - Ergodic 12/02/01 - New Holdables - Private Bot pieces (Legs, Torso, Head)
#define INVENTORY_PRIBOTLEGS			65
#define INVENTORY_PRIBOTTORSO			66
#define INVENTORY_PRIBOTHEAD			67

//PKMOD -Add Weapons. 


//enemy stuff
#define ENEMY_HORIZONTAL_DIST		200
#define ENEMY_HEIGHT				201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES		203

// if running the mission pack
#ifdef MISSIONPACK

//#error "running mission pack"

#endif

//item numbers (make sure they are in sync with bg_itemlist in bg_misc.c)
#define MODELINDEX_ARMORSHARD		1
#define MODELINDEX_ARMORCOMBAT		2
#define MODELINDEX_ARMORBODY		3
#define MODELINDEX_HEALTHSMALL		4
#define MODELINDEX_HEALTH			5
#define MODELINDEX_HEALTHLARGE		6
#define MODELINDEX_HEALTHMEGA		7

#define MODELINDEX_GAUNTLET			8
#define MODELINDEX_SHOTGUN			9
#define MODELINDEX_MACHINEGUN		10
#define MODELINDEX_GRENADELAUNCHER	11
#define MODELINDEX_ROCKETLAUNCHER	12
#define MODELINDEX_LIGHTNING		13
#define MODELINDEX_RAILGUN			14
#define MODELINDEX_PLASMAGUN		15
#define MODELINDEX_BFG10K			16
#define MODELINDEX_GRAPPLINGHOOK	17

#define MODELINDEX_SHELLS			18
#define MODELINDEX_BULLETS			19
#define MODELINDEX_GRENADES			20
#define MODELINDEX_CELLS			21
#define MODELINDEX_LIGHTNINGAMMO	22
#define MODELINDEX_ROCKETS			23
#define MODELINDEX_SLUGS			24
#define MODELINDEX_BFGAMMO			25

#define MODELINDEX_TELEPORTER		26
#define MODELINDEX_MEDKIT			27
//PKMOD - Ergodic - 10/31/01 - new PKA holdables
#define MODELINDEX_RADIATE			28

//PKMOD - Ergodic - 11/23/01 - new PKA holdables
#define MODELINDEX_PERSENTRY		29

//PKMOD - Ergodic 12/02/01 - New Holdables - Private Bot pieces (Legs, Torso, Head)
#define MODELINDEX_PRIBOTLEGS		30
#define MODELINDEX_PRIBOTTORSO		31
#define MODELINDEX_PRIBOTHEAD		32
#define MODELINDEX_QUAD				33
#define MODELINDEX_ENVIRONMENTSUIT	34
#define MODELINDEX_HASTE			35
#define MODELINDEX_INVISIBILITY		36
#define MODELINDEX_REGEN			37
#define MODELINDEX_FLIGHT			38

#define MODELINDEX_REDFLAG			39
#define MODELINDEX_BLUEFLAG			40

//PKMOD -Add Weapon ModelIndexes. 
#define MODELINDEX_GRAVITY			41
#define MODELINDEX_SENTRY			42
#define MODELINDEX_BEARTRAP			43
#define MODELINDEX_AIRFIST			44	
//PKMOD - Ergodic - 12/17/00 rename NAILGUN to PKA_NAILGUN to resolve 1.27g conflict
#define MODELINDEX_PKA_NAILGUN		45
#define MODELINDEX_PKA_NAILS		46
//PKMOD -Add Weapons Modelindexes. 
// mission pack only defines
//PKMOD - Ergodic - 04/15/01 - add beans modelindex
#define MODELINDEX_BEANS			47

//PKMOD - Ergodic - 02/13/02 - add missing PKA weapons/ammo
#define MODELINDEX_PKA_EXPGUN		48
#define MODELINDEX_PKA_EXPSHELLS	49


#define MODELINDEX_KAMIKAZE			50
#define MODELINDEX_PORTAL			51
#define MODELINDEX_INVULNERABILITY	52

#define MODELINDEX_NAILS			53
#define MODELINDEX_MINES			54
#define MODELINDEX_BELT				55

#define MODELINDEX_SCOUT			56
#define MODELINDEX_GUARD			57
#define MODELINDEX_DOUBLER			58
#define MODELINDEX_AMMOREGEN		59

#define MODELINDEX_NEUTRALFLAG		60
#define MODELINDEX_REDCUBE			61
#define MODELINDEX_BLUECUBE			62



//PKMOD - Ergodic 12/18/00 - remove from PKA Inventory
//#define MODELINDEX_NAILGUN			49
//#define MODELINDEX_PROXLAUNCHER		50
//#define MODELINDEX_CHAINGUN			51


//PKAMOD - Ergodic 12/18/00 - remove TA definitions, as of 1.27g merge
/*
#define WEAPONINDEX_GAUNTLET			1
#define WEAPONINDEX_MACHINEGUN			2
#define WEAPONINDEX_SHOTGUN				3
#define WEAPONINDEX_GRENADE_LAUNCHER	4
#define WEAPONINDEX_ROCKET_LAUNCHER		5
#define WEAPONINDEX_LIGHTNING			6
#define WEAPONINDEX_RAILGUN				7
#define WEAPONINDEX_PLASMAGUN			8
#define WEAPONINDEX_BFG					9
#define WEAPONINDEX_GRAPPLING_HOOK		10
#define WEAPONINDEX_NAILGUN				11
#define WEAPONINDEX_PROXLAUNCHER		12
#define WEAPONINDEX_CHAINGUN			13
*/

//PKAMOD - Ergodic 12/18/00 - add PKA definitions, as of 1.27g merge
#define WEAPONINDEX_GAUNTLET			1
#define WEAPONINDEX_MACHINEGUN			2
#define WEAPONINDEX_SHOTGUN				3
#define WEAPONINDEX_AIRFIST				4
#define WEAPONINDEX_NAILGUN				5
#define WEAPONINDEX_GRENADE_LAUNCHER	6
#define WEAPONINDEX_ROCKET_LAUNCHER		7
#define WEAPONINDEX_LIGHTNING			8
#define WEAPONINDEX_RAILGUN				9
#define WEAPONINDEX_GRAPPLING_HOOK		10
#define WEAPONINDEX_GRAVITYWELL			11
#define WEAPONINDEX_SENTRY				12
#define WEAPONINDEX_BEARTRAP			13
#define WEAPONINDEX_BEANS				14
#define WEAPONINDEX_EXPLODING_SHELLS	15
